name: Build Expo Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-cache: true
        eas-cache: true
        packager: pnpm
        patch-watchers: true
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Build Android APK with EAS
      run: eas build --platform android --wait
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Upload Build Info
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: TradeSimPro-Android-Build
        path: './build/'
